[package]
name = "silver"
version = "2.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.4.9"
mime_guess = "2.0.4"
rouille = "3.6.1"
