[package]
name = "silver"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
local-ip-address = "0.4.9"
mime_guess = "2.0.4"
tiny_http = "0.12.0"
